spring:
  cloud:
    aws:
      credentials:
        accessKey: AKIAQ3EGSV5HO7UDUP6D
        secretKey: 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
      s3:
        bucket: codinavi-image
      region:
        static: ap-northeast-2
      stack:
        auto: false
  logging:
    level:
      root: INFO
      org.springframework.web: DEBUG
      com.example: DEBUG
    file:
      name: logs/app.log
  datasource:
    url: "jdbc:mysql://3.34.34.170/codinavi"
    username: "root"
    password: "entmdtkdnsk1679!"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

